spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ehub
    username: postgres
    password: Minh2263@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: be55a54bc6fe880334015c5c58bcbc5197060ebc9706fa9110f9af72245b66d8
  expiration: 86400000