spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ehub
    username: postgres
    password: Minh2263@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:nguyengiangminh99@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:jmqd uvwb yklm cjwk}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      redis:
        enabled: true

jwt:
  secret: be55a54bc6fe880334015c5c58bcbc5197060ebc9706fa9110f9af72245b66d8
  expiration: 86400000
  access-token-ttl: 3600000
  refresh-token-ttl: 604800000
